### ISSUE TITLE
[Request] icons Portugal

### ISSUE THREAD

**Issue by Rootzpower** [wyrm65/resource.images.classificationicons.colour#1]
Hello mate

Can you add icons for Portugal?

**Comment by wyrm65** [comment]
Happy to do so, but will need a little help from you. Only reason there are no Portuguese ratings images is because I could not find any myself.

If you post the required images somewhere and then post a link back I can have an update out in a couple of days.

I will need an image for each rating , preferably in .png format and 64 X 64 pixels in size. Please name each file using the rating name as the file name, for example rating PG would have a file name PG.png. I can figure out the country prefix from what Kodi returns as a country name for Portugal.

If you can find any other country rating icons that I currently don't support please send those along as well, but maybe keep each countries icons in a seperate named directory so I can make sure the right icons end up being used by the correct country.

Many thanks
Wyrm

**Comment by Rootzpower** [comment]
I create a pull request with the icons :)

**Comment by wyrm65** [comment]
Added in release 0.0.4
