### ISSUE TITLE
[Request] icons Mexico

### ISSUE THREAD

**Issue by Chancedashie-GGGG** [wyrm65/resource.images.classificationicons.colour#5]
I Have Found & Discovered [Mexico Ratings](https://en.wikipedia.org/wiki/Direcci%C3%B3n_General_de_Radio,_Televisi%C3%B3n_y_Cinematograf%C3%ADa), Can you or I add icons for That Country?

**Comment by wyrm65** [comment]
Hi @Chancedashie-GGGG ,

I'm very sorry I have only just got onto this.  Due to illness and work commitments that have kept me in the real world, I am only now just catching up on this.

If you have icons for Mexico you can make a pull request to this repo and I will happily accept them. Please name each file in the following manner:   Mexico RatingLabel.png    ( So as an example, "Mexico AA.png" )

I still have to make a pull request for Portugues icons to the upstream repo (Kodi), but I am a complete newb on Github, so I will have to figure out how I make that happen from my end. If you can help with the upstreaming it would be greatly appreciated, otherwise I will look after from my end when I get my head around how that happens.

Many thanks for your patience and for tracking down the icons ( 64 x 64 .png's please).

Look forward to seeing what you have.
Wyrm

**Comment by wyrm65** [comment]
No icons forthcoming, will add when I can find the appropriate icons
